In [1]:
import torch

In [2]:
torch.__version__

'2.2.2'

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
# dimensions are outer bracket to inner bracket, 1 dimension of 3 rows x 3 columns
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.6893, 0.4963, 0.9955, 0.0791],
         [0.5857, 0.5739, 0.8653, 0.0020],
         [0.2896, 0.7663, 0.0737, 0.0308]]),
 torch.float32)

In [21]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [22]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [23]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [24]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_ones = torch.ones_like(input=zero_to_ten)
ten_zeros, ten_ones

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [27]:
# higher precision -> better performance but more compute needed
# lower precision data types -> faster computation, may sacrifice performance
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # default is torch.float32
                               device=None,
                               requires_grad=False) # True records operations performed on the tensor

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

Common issues come from shape mismatch, inconsistent data types, and tensors not being on the same device (CPU, GPU)

In [28]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

In [29]:
some_tensor = torch.rand(3, 4)
print(some_tensor)
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Data type of tensor: {some_tensor.dtype}')
print(f'Device tensor is stored on: {some_tensor.device}')

tensor([[0.1145, 0.0427, 0.1266, 0.4120],
        [0.4692, 0.4526, 0.3074, 0.5046],
        [0.5343, 0.0281, 0.6011, 0.0826]])
Shape of tensor: torch.Size([3, 4])
Data type of tensor: torch.float32
Device tensor is stored on: cpu


In [30]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [31]:
tensor * 10

tensor([10, 20, 30])

In [33]:
tensor = tensor - 10
tensor

tensor([-19, -18, -17])

In [35]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [36]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [37]:
print(tensor, '*', tensor)
print('Equals:', tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
